name: "build-pack"

on:
  push:
    branches:
      - "*"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  buildPack:
    env:
      PACKED_JS_PATH: "dist"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ðŸš€ Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: ðŸš€ Install dependencies
        run: yarn install --frozen-lockfile

      - name: ðŸš€ Build
        run: yarn build

      - name: ðŸš€ Commit packed js
        id: commitPackedJs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ env.PACKED_JS_PATH }}
          git commit -m "Pack with dependencies to ${{ env.PACKED_JS_PATH }}"

      - name: ðŸš€ Push packed js
        if: steps.commitPackedJs.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          force: true
          branch: build
